import type { Kihon } from "./types.ts";

export const kihon = [
  {
    kyu: 10,
    type: "strike",
    name: "Gedan tsuki",
    danishName: "Stød i skridtet",
    direction: "mae",
    target: "gedan",
    weapon: "tsuki",
  },
  {
    kyu: 10,
    type: "strike",
    name: "Chudan tsuki",
    danishName: "Stød i maven",
    direction: "mae",
    target: "chudan",
    weapon: "tsuki",
  },
  {
    kyu: 10,
    type: "strike",
    name: "Jodan tsuki",
    danishName: "Stød i hovedet",
    direction: "mae",
    target: "jodan",
    weapon: "tsuki",
  },
  {
    kyu: 10,
    type: "strike",
    name: "Morote tsuki",
    danishName: "Dobbelt stød",
    direction: "mae",
    target: ["jodan", "chudan", "gedan"],
    weapon: "tsuki",
  },
  {
    kyu: 9,
    type: "strike",
    name: "Ago uchi",
    danishName: "Snapstød mod hagen",
    direction: "mae",
    target: "jodan",
    weapon: "tsuki",
  },
  {
    kyu: 8,
    type: "strike",
    name: "Seiken shita tsuki",
    danishName: "Lavt omvendt stød",
    direction: "mae",
    target: "chudan",
    weapon: "tsuki",
  },
  {
    kyu: 6,
    type: "strike",
    name: "Mawashi uchi",
    danishName: "Cirkelslag",
    direction: ["mawashi", "uraken"],
    target: "jodan",
    weapon: "tsuki",
  },
  {
    kyu: 6,
    type: "strike",
    name: "Uraken shomen uchi",
    danishName: "Fremadrettet omvendt knoslag",
    direction: "uraken",
    target: "jodan",
    weapon: "tsuki",
  },
  {
    kyu: 6,
    type: "strike",
    name: "Uraken hizo uchi",
    danishName: "Lavt omvendt knoslag mod ribben",
    direction: "uraken",
    target: "chudan",
    weapon: "tsuki",
  },
  {
    kyu: 6,
    type: "strike",
    name: "Uraken sayu uchi",
    danishName: "Sidelæns omvendt knoslag",
    direction: ["uraken", "yoko"],
    target: "chudan",
    weapon: "tsuki",
  },
  {
    kyu: 5,
    type: "strike",
    name: "Jodan hiji uchi",
    danishName: "Albueslag mod hovedet",
    direction: "mae",
    target: "jodan",
    weapon: "hiji",
  },
  {
    kyu: 5,
    type: "strike",
    name: "Chudan hiji uchi",
    danishName: "Albueslag mod maven",
    direction: "mae",
    target: "chudan",
    weapon: "hiji",
  },
  {
    kyu: 5,
    type: "strike",
    name: "Hiji age uchi",
    danishName: "Opadgående albueslag",
    direction: "age",
    target: "chudan",
    weapon: "hiji",
  },
  {
    kyu: 5,
    type: "strike",
    name: "Hiji oroshi uchi",
    danishName: "Nedadgående albueslag",
    direction: "oroshi",
    target: "jodan",
    weapon: "hiji",
  },
  {
    kyu: 4,
    type: "strike",
    name: "Shuto gammen soto uchi",
    danishName: "Udvendig håndkantslag i hoved",
    direction: "soto",
    target: "jodan",
    weapon: "shuto",
  },
  {
    kyu: 4,
    type: "strike",
    name: "Shuto gammen uchi uchi",
    danishName: "Indvendig håndkantslag i hoved",
    direction: "uchi",
    target: "jodan",
    weapon: "shuto",
  },
  {
    kyu: 4,
    type: "strike",
    name: "Shuto hizo uchi",
    danishName: "Udvendig håndkantslag i ribben",
    direction: "soto",
    target: "chudan",
    weapon: "shuto",
  },
  {
    kyu: 4,
    type: "strike",
    name: "Shuto sakotsu uchi",
    danishName: "Nedadgående håndkantslag",
    direction: "oroshi",
    target: "jodan",
    weapon: "shuto",
  },
  {
    kyu: 3,
    type: "strike",
    name: "Jodan shotei uchi",
    danishName: "Slag med håndfladekant i hoved",
    direction: "mae",
    target: "jodan",
    weapon: "shotei",
  },
  {
    kyu: 3,
    type: "strike",
    name: "Chudan shotei uchi",
    danishName: "Slag med håndfladekant i mave",
    direction: "mae",
    target: "chudan",
    weapon: "shotei",
  },
  {
    kyu: 3,
    type: "strike",
    name: "Gedan shotei uchi",
    danishName: "Slag med håndfladekant i skridt",
    direction: "mae",
    target: "gedan",
    weapon: "shotei",
  },
  {
    kyu: 1,
    type: "strike",
    name: "Jodan koken uchi",
    danishName: "Håndledslag i hoved",
    direction: "mae",
    target: "jodan",
    weapon: "koken",
  },
  {
    kyu: 1,
    type: "strike",
    name: "Chudan koken uchi",
    danishName: "Håndledslag i mave",
    direction: "mae",
    target: "chudan",
    weapon: "koken",
  },
  {
    kyu: 1,
    type: "strike",
    name: "Gedan koken uchi",
    danishName: "Håndledslag i skridt",
    direction: "mae",
    target: "gedan",
    weapon: "koken",
  },
  {
    kyu: 10,
    type: "kick",
    name: "Hiza geri",
    danishName: "Knæspark",
    direction: "mae",
    target: "chudan",
    weapon: "hiza",
  },
  {
    kyu: 10,
    type: "kick",
    name: "Kin geri",
    danishName: "Skridtspark",
    direction: "mae",
    target: "gedan",
    weapon: "heisoku",
  },
  {
    kyu: 10,
    type: "kick",
    name: "Chudan mae geri",
    danishName: "Front spark i maven",
    direction: "mae",
    target: "chudan",
    weapon: "chosuko",
  },
  {
    kyu: 9,
    type: "kick",
    name: "Jodan mae geri",
    danishName: "Front spark i hovedet",
    direction: "mae",
    target: "jodan",
    weapon: "chosuko",
  },
  {
    kyu: 8,
    type: "kick",
    name: "Hiza mawashi geri",
    danishName: "Cirkel knæspark",
    direction: "mawashi",
    target: "chudan",
    weapon: "hiza",
  },
  {
    kyu: 8,
    type: "kick",
    name: "Chudan mawashi geri",
    danishName: "Cirkelspark i maven",
    direction: "mawashi",
    target: "chudan",
    weapon: "heisoku",
  },
  {
    kyu: 8,
    type: "kick",
    name: "Gedan geri",
    danishName: "Lårspark",
    direction: "mawashi",
    target: "gedan",
    weapon: "heisoku",
  },
  {
    kyu: 7,
    type: "kick",
    name: "Mae keage geri",
    danishName: "Strakt fronspark",
    direction: "mae",
    target: "jodan",
    weapon: "chosuko",
  },
  {
    kyu: 7,
    type: "kick",
    name: "Sokuto yoko keage geri",
    danishName: "Strakt sidelæns fronspark",
    direction: ["yoko", "keage"],
    target: "jodan",
    weapon: "sokuto",
  },
  {
    kyu: 7,
    type: "kick",
    name: "Jodan mawashi geri",
    danishName: "Cirkelspark i hovedet",
    direction: "mawashi",
    target: "jodan",
    weapon: "heisoku",
  },
  {
    kyu: 7,
    type: "kick",
    name: "Sokuto uchi mawashi geri",
    danishName: "Indvendig strakt cirkelspark",
    direction: ["mawashi", "keage", "uchi"],
    target: "jodan",
    weapon: "sokuto",
  },
  {
    kyu: 7,
    type: "kick",
    name: "Teisoku soto mawashi geri",
    danishName: "Udvendig strakt cirkelspark",
    direction: ["mawashi", "keage", "soto"],
    target: "jodan",
    weapon: "teisoku",
  },
  {
    kyu: 6,
    type: "kick",
    name: "Kansetsu geri",
    danishName: "Lavt sidelæns spark",
    direction: "yoko",
    target: "gedan",
    weapon: "sokuto",
  },
  {
    kyu: 6,
    type: "kick",
    name: "Chudan yoko geri",
    danishName: "Sidelæns spark i maven",
    direction: "yoko",
    target: "chudan",
    weapon: "sokuto",
  },
  {
    kyu: 6,
    type: "kick",
    name: "Oroshi soto kakato geri",
    danishName: "Udvendig nedadgående hælspark",
    direction: ["oroshi", "keage", "soto"],
    target: "jodan",
    weapon: "kakato",
  },
  {
    kyu: 6,
    type: "kick",
    name: "Oroshi uchi kakato geri",
    danishName: "Indvendig nedadgående hælspark",
    direction: ["oroshi", "keage", "uchi"],
    target: "jodan",
    weapon: "kakato",
  },
  {
    kyu: 5,
    type: "kick",
    name: "Ushiro geri",
    danishName: "Baglæns spark",
    direction: "ushiro",
    target: "chudan",
  },
  {
    kyu: 5,
    type: "kick",
    name: "Jodan yoko geri",
    danishName: "Sidelæns spark i hovedet",
    direction: "yoko",
    target: "jodan",
    weapon: "sokuto",
  },
  {
    kyu: 4,
    type: "kick",
    name: "Mae tobi geri",
    danishName: "Flyvende frontspark",
    direction: ["mae", "tobi"],
    target: "jodan",
    weapon: "chosuko",
  },
  {
    kyu: 3,
    type: "kick",
    name: "Ushiro mawashi geri",
    danishName: "Baglæns cirkelspark",
    direction: ["ushiro", "mawashi"],
    target: "chudan",
    weapon: "kakato",
  },
  {
    kyu: 3,
    type: "kick",
    name: "Mawashi tobi geri",
    danishName: "Flyvende cirkelspark",
    direction: ["mawashi", "tobi"],
    target: "jodan",
    weapon: "heisoku",
  },
  {
    kyu: 3,
    type: "kick",
    name: "Nidan mae tobi geri",
    danishName: "Dobbelt flyvende cirkelspark",
    direction: ["mae", "tobi"],
    target: "jodan",
    weapon: "chosuko",
  },
  {
    kyu: 2,
    type: "kick",
    name: "Jodan uchi heisoku geri",
    danishName: "Indvendigt cirkelspark med vristen",
    direction: "uchi",
    target: "jodan",
    weapon: "heisoku",
  },
  {
    kyu: 2,
    type: "kick",
    name: "Ushiro tobi geri",
    danishName: "Baglæns flyvende spark",
    direction: ["ushiro", "tobi"],
    target: "chudan",
    weapon: "kakato",
  },
  {
    kyu: 1,
    type: "kick",
    name: "Ushiro mawashi tobi geri",
    danishName: "Baglæns flyvende cirkelspark",
    direction: ["ushiro", "mawashi", "tobi"],
    target: "chudan",
    weapon: "kakato",
  },
  {
    kyu: 10,
    type: "block",
    name: "Jodan uke",
    danishName: "Opadgående parade",
    direction: "age",
    target: "jodan",
    weapon: "tsuki",
  },
  {
    kyu: 10,
    type: "block",
    name: "Gedan barai",
    danishName: "Nedadgående parade",
    direction: "oroshi",
    target: "gedan",
    weapon: "tsuki",
  },
  {
    kyu: 10,
    type: "block",
    name: "Seiken morote gedan barai",
    danishName: "Dobbelt nedadgående parade",
    direction: "oroshi",
    target: "gedan",
    weapon: "tsuki",
  },
  {
    kyu: 9,
    type: "block",
    name: "Soto uke",
    danishName: "Udvendig parade",
    direction: "soto",
    target: "chudan",
    weapon: "tsuki",
  },
  {
    kyu: 9,
    type: "block",
    name: "Uchi uke",
    danishName: "Indvendig parade",
    direction: "uchi",
    target: "chudan",
    weapon: "tsuki",
  },
  {
    kyu: 8,
    type: "block",
    name: "Uchi uke gedan barai",
    danishName: "Indvendig og nedadgående parade",
    direction: ["uchi", "oroshi"],
    target: ["chudan", "gedan"],
    weapon: "tsuki",
  },
  {
    kyu: 7,
    type: "block",
    name: "Mawashi gedan barai",
    danishName: "Cirkulær nedadgående parade",
    direction: "mawashi",
    target: "gedan",
    weapon: "tsuki",
  },
  {
    kyu: 7,
    type: "block",
    name: "Shuto mawashi uke",
    danishName: "Cirkelparade med håndkanten",
    direction: "mawashi",
    target: "chudan",
    weapon: "shuto",
  },
  {
    kyu: 4,
    type: "block",
    name: "Mae mawashi uke",
    danishName: "Dobbelt cirkelparade",
    direction: ["mae", "mawashi"],
    target: "chudan",
    weapon: "shotei",
  },
  {
    kyu: 2,
    type: "block",
    name: "Jodan shotei uke",
    danishName: "Parade med håndfladekant i hoved",
    direction: "age",
    target: "jodan",
    weapon: "shotei",
  },
  {
    kyu: 2,
    type: "block",
    name: "Chudan shotei uke",
    danishName: "Parade med håndfladekant i mave",
    direction: "mae",
    target: "chudan",
    weapon: "shotei",
  },
  {
    kyu: 2,
    type: "block",
    name: "Gedan shotei uke",
    danishName: "Parade med håndfladekant i skridt",
    direction: "oroshi",
    target: "gedan",
    weapon: "shotei",
  },
  {
    kyu: 1,
    type: "block",
    name: "Jodan koken uke",
    danishName: "Håndledsparade i hoved",
    direction: "age",
    target: "jodan",
    weapon: "koken",
  },
  {
    kyu: 1,
    type: "block",
    name: "Chudan koken uke",
    danishName: "Håndledsparade i mave",
    direction: "mae",
    target: "chudan",
    weapon: "koken",
  },
  {
    kyu: 1,
    type: "block",
    name: "Gedan koken uke",
    danishName: "Håndledsparade i skridt",
    direction: "oroshi",
    target: "gedan",
    weapon: "koken",
  },
  {
    kyu: 10,
    type: "stance",
    name: "Fudo dachi",
    danishName: "Normal stilling",
    curriculumOnly: true,
  },
  {
    kyu: 10,
    type: "stance",
    name: "Zenkutso dachi",
    danishName: "Forlæns stilling",
  },
  {
    kyu: 10,
    type: "stance",
    name: "Heiko dachi",
    danishName: "Stilling med parallelle fødder",
    curriculumOnly: true,
  },
  {
    kyu: 10,
    type: "stance",
    name: "Uchi hachi-ji dachi",
    danishName: "Stilling med indadrettede fødder",
    curriculumOnly: true,
  },
  {
    kyu: 10,
    type: "stance",
    name: "Yoi dachi",
    danishName: "Klar stilling",
    curriculumOnly: true,
  },
  {
    kyu: 10,
    type: "stance",
    name: "Kumite dachi",
    danishName: "Kamp stilling",
  },
  {
    kyu: 9,
    type: "stance",
    name: "Sanchin dachi",
    danishName: "Basis stilling",
  },
  {
    kyu: 9,
    type: "stance",
    name: "Kokutsu dachi",
    danishName: "Baglæns stilling",
  },
  {
    kyu: 8,
    type: "stance",
    name: "Kiba dachi",
    danishName: "Ride stilling",
  },
  {
    kyu: 7,
    type: "stance",
    name: "Neko ashi dachi",
    danishName: "Kat stilling",
  },
  {
    kyu: 7,
    type: "stance",
    name: "Musubi dachi",
    danishName: "Stilling med samlede hæle",
    curriculumOnly: true,
  },
  {
    kyu: 6,
    type: "stance",
    name: "Tsuru ashi dachi",
    danishName: "Stilling på et ben",
    curriculumOnly: true,
  },
  {
    kyu: 6,
    type: "stance",
    name: "Heisoku dachi",
    danishName: "Stilling med samlede fødder",
    curriculumOnly: true,
  },
  {
    kyu: 5,
    type: "stance",
    name: "Kake dachi",
    danishName: "Kryds stilling",
  },
  {
    kyu: 1,
    type: "stance",
    name: "Moro ashi dachi",
    danishName: "Forskudte parallelle fødder",
  },
] as Kihon[];
