import type { Kihon } from "./types.ts";

export const kihon = [
  {
    kyu: 10,
    type: "strike",
    name: "Gedan tsuki",
    danishName: "Stød i skridtet",
  },
  {
    kyu: 10,
    type: "strike",
    name: "Chudan tsuki",
    danishName: "Stød i maven",
  },
  {
    kyu: 10,
    type: "strike",
    name: "Jodan tsuki",
    danishName: "Stød i hovedet",
  },
  {
    kyu: 10,
    type: "strike",
    name: "Morote tsuki",
    danishName: "Dobbelt stød",
  },
  {
    kyu: 9,
    type: "strike",
    name: "Ago uchi",
    danishName: "Snapstød mod hagen",
  },
  {
    kyu: 8,
    type: "strike",
    name: "Seiken shita tsuki",
    danishName: "Lavt omvendt stød",
  },
  {
    kyu: 6,
    type: "strike",
    name: "Mawashi uchi",
    danishName: "Cirkelslag",
  },
  {
    kyu: 6,
    type: "strike",
    name: "Uraken shomen uchi",
    danishName: "Fremadrettet omvendt knoslag",
  },
  {
    kyu: 6,
    type: "strike",
    name: "Uraken hizo uchi",
    danishName: "Lavt omvendt knoslag mod ribben",
  },
  {
    kyu: 6,
    type: "strike",
    name: "Uraken sayu uchi",
    danishName: "Sidelæns omvendt knoslag",
  },
  {
    kyu: 5,
    type: "strike",
    name: "Jodan hiji uchi",
    danishName: "Albueslag mod hovedet",
  },
  {
    kyu: 5,
    type: "strike",
    name: "Chudan hiji uchi",
    danishName: "Albueslag mod maven",
  },
  {
    kyu: 5,
    type: "strike",
    name: "Hiji age uchi",
    danishName: "Opadgående albueslag",
  },
  {
    kyu: 5,
    type: "strike",
    name: "Hiji oroshi uchi",
    danishName: "Nedadgående albueslag",
  },
  {
    kyu: 4,
    type: "strike",
    name: "Shuto gammen soto uchi",
    danishName: "Udvendig håndkantslag i hoved",
  },
  {
    kyu: 4,
    type: "strike",
    name: "Shuto gammen uchi uchi",
    danishName: "Indvendig håndkantslag i hoved",
  },
  {
    kyu: 4,
    type: "strike",
    name: "Shuto hizo uchi",
    danishName: "Udvendig håndkantslag i ribben",
  },
  {
    kyu: 4,
    type: "strike",
    name: "Shuto sakotsu uchi",
    danishName: "Nedadgående håndkantslag",
  },
  {
    kyu: 3,
    type: "strike",
    name: "Jodan shotei uchi",
    danishName: "Slag med håndfladekant i hoved",
  },
  {
    kyu: 3,
    type: "strike",
    name: "Chudan shotei uchi",
    danishName: "Slag med håndfladekant i mave",
  },
  {
    kyu: 3,
    type: "strike",
    name: "Gedan shotei uchi",
    danishName: "Slag med håndfladekant i skridt",
  },
  {
    kyu: 1,
    type: "strike",
    name: "Jodan koken uchi",
    danishName: "Håndledslag i hoved",
  },
  {
    kyu: 1,
    type: "strike",
    name: "Chudan koken uchi",
    danishName: "Håndledslag i mave",
  },
  {
    kyu: 1,
    type: "strike",
    name: "Gedan koken uchi",
    danishName: "Håndledslag i skridt",
  },
  {
    kyu: 10,
    type: "kick",
    name: "Hiza geri",
    danishName: "Knæspark",
  },
  {
    kyu: 10,
    type: "kick",
    name: "Kin geri",
    danishName: "Skridtspark",
  },
  {
    kyu: 10,
    type: "kick",
    name: "Chudan mae geri",
    danishName: "Front spark i maven",
  },
  {
    kyu: 9,
    type: "kick",
    name: "Jodan mae geri",
    danishName: "Front spark i hovedet",
  },
  {
    kyu: 8,
    type: "kick",
    name: "Hiza mawashi geri",
    danishName: "Cirkel knæspark",
  },
  {
    kyu: 8,
    type: "kick",
    name: "Chudan mawashi geri",
    danishName: "Cirkelspark i maven",
  },
  {
    kyu: 8,
    type: "kick",
    name: "Gedan geri",
    danishName: "Lårspark",
  },
  {
    kyu: 7,
    type: "kick",
    name: "Mae keage geri",
    danishName: "Strakt fronspark",
  },
  {
    kyu: 7,
    type: "kick",
    name: "Sokuto yoko keage geri",
    danishName: "Strakt sidelæns fronspark",
  },
  {
    kyu: 7,
    type: "kick",
    name: "Jodan mawashi geri",
    danishName: "Cirkelspark i hovedet",
  },
  {
    kyu: 7,
    type: "kick",
    name: "Sokuto uchi mawashi geri",
    danishName: "Indvendig strakt cirkelspark",
  },
  {
    kyu: 7,
    type: "kick",
    name: "Teisoku soto mawashi geri",
    danishName: "Udvendig strakt cirkelspark",
  },
  {
    kyu: 6,
    type: "kick",
    name: "Kansetsu geri",
    danishName: "Lavt sidelæns spark",
  },
  {
    kyu: 6,
    type: "kick",
    name: "Chudan yoko geri",
    danishName: "Sidelæns spark i maven",
  },
  {
    kyu: 6,
    type: "kick",
    name: "Oroshi soto kakato geri",
    danishName: "Udvendig nedadgående hælspark",
  },
  {
    kyu: 6,
    type: "kick",
    name: "Oroshi uchi kakato geri",
    danishName: "Indvendig nedadgående hælspark",
  },
  {
    kyu: 5,
    type: "kick",
    name: "Ushiro geri",
    danishName: "Baglæns spark",
  },
  {
    kyu: 5,
    type: "kick",
    name: "Jodan yoko geri",
    danishName: "Sidelæns spark i hovedet",
  },
  {
    kyu: 4,
    type: "kick",
    name: "Mae tobi geri",
    danishName: "Flyvende frontspark",
  },
  {
    kyu: 3,
    type: "kick",
    name: "Ushiro mawashi geri",
    danishName: "Baglæns cirkelspark",
  },
  {
    kyu: 3,
    type: "kick",
    name: "Mawashi tobi geri",
    danishName: "Flyvende cirkelspark",
  },
  {
    kyu: 3,
    type: "kick",
    name: "Nidan mae tobi geri",
    danishName: "Dobbelt flyvende cirkelspark",
  },
  {
    kyu: 2,
    type: "kick",
    name: "Jodan uchi heisoku geri",
    danishName: "Indvendigt cirkelspark med vristen",
  },
  {
    kyu: 2,
    type: "kick",
    name: "Ushiro tobi geri",
    danishName: "Baglæns flyvende spark",
  },
  {
    kyu: 1,
    type: "kick",
    name: "Ushiro mawashi tobi geri",
    danishName: "Baglæns flyvende cirkelspark",
  },
  {
    kyu: 10,
    type: "block",
    name: "Jodan uke",
    danishName: "Opadgående parade",
  },
  {
    kyu: 10,
    type: "block",
    name: "Gedan barai",
    danishName: "Nedadgående parade",
  },
  {
    kyu: 10,
    type: "block",
    name: "Seiken morote gedan barai",
    danishName: "Dobbelt nedadgående parade",
  },
  {
    kyu: 9,
    type: "block",
    name: "Soto uke",
    danishName: "Udvendig parade",
  },
  {
    kyu: 9,
    type: "block",
    name: "Uchi uke",
    danishName: "Indvendig parade",
  },
  {
    kyu: 8,
    type: "block",
    name: "Uchi uke gedan barai",
    danishName: "Indvendig og nedadgående parade",
  },
  {
    kyu: 7,
    type: "block",
    name: "Mawashi gedan barai",
    danishName: "Cirkulær nedadgående parade",
  },
  {
    kyu: 7,
    type: "block",
    name: "Shuto mawashi uke",
    danishName: "Cirkelparade med håndkanten",
  },
  {
    kyu: 4,
    type: "block",
    name: "Mae mawashi uke",
    danishName: "Dobbelt cirkelparade",
  },
  {
    kyu: 2,
    type: "block",
    name: "Jodan shotei uke",
    danishName: "Parade med håndfladekant i hoved",
  },
  {
    kyu: 2,
    type: "block",
    name: "Chudan shotei uke",
    danishName: "Parade med håndfladekant i mave",
  },
  {
    kyu: 2,
    type: "block",
    name: "Gedan shotei uke",
    danishName: "Parade med håndfladekant i skridt",
  },
  {
    kyu: 1,
    type: "block",
    name: "Jodan koken uke",
    danishName: "Håndledsparade i hoved",
  },
  {
    kyu: 1,
    type: "block",
    name: "Chudan koken uke",
    danishName: "Håndledsparade i mave",
  },
  {
    kyu: 1,
    type: "block",
    name: "Gedan koken uke",
    danishName: "Håndledsparade i skridt",
  },
  {
    kyu: 10,
    type: "stance",
    name: "Fudo dachi",
    danishName: "Normal stilling",
    curriculumOnly: true,
  },
  {
    kyu: 10,
    type: "stance",
    name: "Zenkutso dachi",
    danishName: "Forlæns stilling",
  },
  {
    kyu: 10,
    type: "stance",
    name: "Heiko dachi",
    danishName: "Stilling med parallelle fødder",
    curriculumOnly: true,
  },
  {
    kyu: 10,
    type: "stance",
    name: "Uchi hachi-ji dachi",
    danishName: "Stilling med indadrettede fødder",
    curriculumOnly: true,
  },
  {
    kyu: 10,
    type: "stance",
    name: "Yoi dachi",
    danishName: "Klar stilling",
    curriculumOnly: true,
  },
  {
    kyu: 10,
    type: "stance",
    name: "Kumite dachi",
    danishName: "Kamp stilling",
  },
  {
    kyu: 9,
    type: "stance",
    name: "Sanchin dachi",
    danishName: "Basis stilling",
  },
  {
    kyu: 9,
    type: "stance",
    name: "Kokutsu dachi",
    danishName: "Baglæns stilling",
  },
  {
    kyu: 8,
    type: "stance",
    name: "Kiba dachi",
    danishName: "Ride stilling",
  },
  {
    kyu: 7,
    type: "stance",
    name: "Neko ashi dachi",
    danishName: "Kat stilling",
  },
  {
    kyu: 7,
    type: "stance",
    name: "Musubi dachi",
    danishName: "Stilling med samlede hæle",
  },
  {
    kyu: 6,
    type: "stance",
    name: "Tsuru ashi dachi",
    danishName: "Stilling på et ben",
    curriculumOnly: true,
  },
  {
    kyu: 6,
    type: "stance",
    name: "Heisoku dachi",
    danishName: "Stilling med samlede fødder",
    curriculumOnly: true,
  },
  {
    kyu: 5,
    type: "stance",
    name: "Kake dachi",
    danishName: "Kryds stilling",
  },
  {
    kyu: 1,
    type: "stance",
    name: "Moro ashi dachi",
    danishName: "Forskudte parallelle fødder",
  },
] as Kihon[];
